version: '3.3'
services:
  collaborative-web:
    restart: always
    image: swiftlatex/collaborative
    container_name: collaborative
    depends_on:
      - mongo_server
    ports:
      - 18080:18080
    environment:
      MONGODB_URL: mongodb://mongo_server:27017/docstore
      SIGNKEY: random
  mongo_server:
    restart: always
    image: mongo
    container_name: mongo_server
    expose:
      - 27017
    volumes:
      - ~/mongo_data:/data/db
